### ISSUE TITLE
Final call for Beijing talk submissions

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/live.nodejs.org#44]
@nodejs/nodejs-cn We're rounding out the call for talks for [Node Live Beijing](http://live.nodejs.org/events/beijing.html)(selection is upon us!). Do y'all have any recommendations of folks around Beijing you think would be a great speaker on Node core subjects? We'd love to see more talks from Node working groups!

**Comment by hailiang-wang** [comment]
@hackygolucky 

Wow, I just check this issue in time, may I ask what qualifications we should provide to apply a topic ? Is the speech in English ? Or the presentations should be in English ? 

I have hold NodeJS Meetups and parties monthly since May 2015, I am also a developer building applications with NodeJS. So, we have a collection of slides and pictures for these parties.

https://git.oschina.net/ubiware/node-party

**Comment by hackygolucky** [comment]
@Samurais We will have a translator speaking Mandarin for any English speaking talks. We expect and encourage those who feel more comfortable speaking Mandarin to do so.

We would love to hear more from people who are working on the core language or a working group under the technical steering committee(TSC). 

Let's follow up through email about the after party. That sounds fun!
